# SPDX-License-Identifier: GPL-2.0
PACKAGE_NAME="arducam-obisp"
PACKAGE_VERSION="1.0.0"
BUILT_MODULE_NAME[0]="arducam"
BUILT_MODULE_LOCATION[0]="sourceCode"
DEST_MODULE_LOCATION[0]="/kernel/drivers/media/i2c"
AUTOINSTALL="yes"
MAKE[0]="make -C sourceCode KDIR=/lib/modules/${kernelver}/build"
CLEAN="make -C sourceCode KDIR=/lib/modules/${kernelver}/build clean"
